name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        pip install --upgrade pip pipenv
        pipenv sync --dev
    - name: Run test
      run: pipenv run pytest
    - name: Coverage report
      run: pipenv run python-codacy-coverage -r coverage.xml
